name: Deploy to Staging
on:
  push:
    branches: [ staging ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/ssh-setup
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install PM2
      run: npm i pm2
    - name: Deploy
      run: pm2 deploy ecosystem.staging.config.js staging